### PR TITLE
Upgrade scallop

### PR DESCRIPTION
**Pull request by ekoi**
fixes EASY-1049 Upgrade scallop
#### When applied it will
- use the version 1.0.1 of scallop
#### Where should the reviewer @DANS-KNAW/easy start?

Conf   pom
#### How should this be manually tested?
- execute ./run.sh --help (provide first the app.home, see https://github.com/DANS-KNAW/easy-dtap#running-a-new-component)
#### related pull requests on github

| repo | PR |
| --- | --- |
| easy- | [PR#](PRlink) |

### CODE REVIEW

**Comment by rvanheest** [comment]
Looks good to me.

However, I see that Scallop in the meantime has moved on to newer releases. Currently they are at v2.0.2 (https://github.com/scallop/scallop/releases). Would it make sense to move to this version. Maybe we should take a look at the change logs and see what has changed/improved, whether bugs in v1.0.1 are found/solved and what effort it would take from our side to change to the newest version quickly.

@janvanmansum @jo-pol @ekoi I would like to hear your opinions on this as you seem to be most into this library...

**Comment by jo-pol** [comment]
There is indeed another breaking change, see: 

* https://github.com/scallop/scallop/commit/3422e7e1d99de4ff499d2bac91a3d1f91b3df229
* https://github.com/scallop/scallop/issues/110

On various occasions we indeed distinguish between files that should exist, may exist or should not exist. Because of the former validation, the files that don't need to exist were specified as strings, these should change too.

First of all we need an inventory of all situations were file names are wanted and  establish new conventions.

**Comment by janvanmansum** [comment]
I hadn't even thought of that. Good point @jo-pol. @ekoi, please take her comment into account.

**Comment by rvanheest** [comment]
As I'll take over this issue and the rest of EASY-1049, I'll talk with @jo-pol tomorrow about this.

**Comment by rvanheest** [comment]
I upgraded to 2.0.2 in the `pom.xml`. No further reason to not merge this PR!

**Pull request merged**
